.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/question.md
.github/OWNERS
.github/PULL_REQUEST_TEMPLATE.md
MAINTAINERS.md
code-of-conduct.md
maintainer_guidelines.md

Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>

adding some initial docs

---

src/apps/Synapse.Cli/Commands/Systems/Installs/NativeInstallCommand.cs
src/runtime/Synapse.Runtime.Native/Services/NativeRuntimeHost.cs

Fixes invalid uris for both CLI and Native Runtime Host projects

CLI and Native Runtime Host fix

---

README.md

Fixed instructions on how to run Synapse on Docker

Fixed instructions on how to run Synapse on Docker

---

README.md

Minor fixes to the Readme file

Minor fixes to the Readme file

---

README.md

Replaced versioned download uri by latest

Replaced versioned download uri by latest

---

src/apps/Synapse.Cli/Commands/Systems/Installs/NativeInstallCommand.cs
src/runtime/Synapse.Runtime.Docker/Services/DockerRuntimeHost.cs

Fixed CLI NativeInstall command, which had a wrongly typed 'Directory' option (bool instead of string)

Fixed CLI NativeInstall command

---

src/apps/Synapse.Server/Dockerfile
src/apps/Synapse.Server/Properties/launchSettings.json

Server Docker image fix

---

src/apps/Synapse.Cli/Commands/Systems/InstallCommand.cs
src/apps/Synapse.Cli/Commands/Systems/Installs/DockerInstallCommand.cs
src/apps/Synapse.Cli/Commands/Systems/Installs/NativeInstallCommand.cs
src/apps/Synapse.Server/appsettings.json
src/core/Synapse.Application/Configuration/CloudEventOptions.cs
src/core/Synapse.Application/Configuration/CloudEventSinkOptions.cs
src/core/Synapse.Application/Configuration/SynapseApplicationBuilder.cs
src/core/Synapse.Integration/EnvironmentVariables.cs

Added a new command to install Synapse on Docker

feat(CLI): Added a new command to install Synapse on Docker

---

Neuroglia.Blazor.Dagre/DagreGraph.razor

- added titles to center and zoom to fit buttons, closes #34

Added titles on center and zoom to fit buttons

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Native/Services/NativeRuntimeHost.cs
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

- Fixed the worker download uri to match the current application's version
- Updated solution version

fix(Runtime.Native): Fixed the worker download uri to match the current application's version

---

.gitignore
Synapse.sln
deployment/docker-compose/docker-compose.dcproj
deployment/docker-compose/docker-compose.yml
src/apps/Synapse.Server/Properties/launchSettings.json
src/apps/Synapse.Server/Synapse.Server.csproj
src/core/Synapse.Application/Commands/Correlations/v1/V1CorrelateEventCommand.cs
src/core/Synapse.Application/Queries/Correlations/V1GetEventCorrelationsQuery.cs
src/core/Synapse.Application/Services/PluginHandle.cs
src/core/Synapse.Application/Services/PluginManager.cs
src/core/Synapse.Application/Utilities/TarGzPackage.cs
src/core/Synapse.Infrastructure/Plugins/PluginMetadata.cs
src/core/Synapse.Integration/Models/v1/V1Correlation.cs
src/core/Synapse.Integration/Models/v1/V1CorrelationCondition.cs
src/core/Synapse.Integration/Models/v1/V1Event.cs
src/core/Synapse.Integration/Models/v1/V1EventFilter.cs
src/runtime/Synapse.Runtime.Docker/Services/DockerRuntimeHost.cs

Adds docker-compose support for easy deployment of Synapse with persistence enabled (EventStore/MongoDB)
Easy deployment of Synapse with persistence enabled (EventStore/MongoDB)

Added docker-compose support

---

src/apps/Synapse.Worker/Services/Processors/BranchProcessor.cs
src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs
src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs
src/apps/Synapse.Worker/Services/WorkflowRuntime.cs

Fixed Branch, Operation and EventState processors by cancelling sub processors upon unhandled fault

fix(Worker): Fixed Branch, Operation and EventState processors by cancelling sub processors upon unhandled fault

---

src/dashboard/Synapse.Dashboard/Pages/Workflows/View.razor

fix(Dashboard): Prevented null reference access of workflow instance activities in workflow view

---

Synapse.sln

Removed kubernetes.csproj from solution
Includes fixes that were left out in previous CodeQL fix

Fixed CodeQL pipeline

---

src/dashboard/Synapse.Dashboard/Extensions/GraphExtensions.cs
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/IActionNodeViewModel.cs

Displayed activity counter badges on actions in the workflow diagram.
Closes serverlessworkflow#73

fix(Dashboard): Fixed actions activity badges display

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

Updates solution packages to latest Neuroglia Framework releases

Updated solution packages to latest Neuroglia Framework releases

---

src/apps/Synapse.Server/Dockerfile

Fixed the Dockerfile, which was invoking a non-existing assembly, and was not referencing the proper projects

Fixed the Dockerfile, which was invoking a non-existing assembly, and was not referencing the proper projects

---

.github/workflows/publish.yml

Fixed the publish pipeline

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Updated solution to v0.1.4

---

src/apps/Synapse.Worker/Services/WorkflowRuntimeContext.cs

Minor fixes to the WorkflowRuntimeContext's method names

Minor fixes to the WorkflowRuntimeContext's method names

---

src/dashboard/Synapse.Dashboard/Pages/Workflows/View.razor

Fix the broken instance view when it's reloaded

fix(Dashboard): Fixed reloading the instance view

---

src/dashboard/Synapse.Dashboard/Pages/Workflows/View.razor

Prevented workflow view to hang forever on reload

fix(Dashboard): Prevented workflow view to hang forever on reload

---

src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj

Updated ServerlessWorkflow SDK package to latest version

Updated ServerlessWorkflow SDK package to latest version

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/App.razor
src/dashboard/Synapse.Dashboard/Features/V1WorkflowActivityCollectionState.cs
src/dashboard/Synapse.Dashboard/Features/WorkflowInstances/WorkflowInstanceLogs/WorkflowInstanceLogs.razor
src/dashboard/Synapse.Dashboard/Features/WorkflowInstances/WorkflowInstanceToolbar/WorkflowInstanceToolbar.razor
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

Add contextual actions to instance view

Adds contextual actions to instance view

---

src/dashboard/Synapse.Dashboard/Extensions/GraphExtensions.cs

Highlighted visited switch case nodes

Highlighted visited switch case nodes

---

src/dashboard/Synapse.Dashboard/Features/Shared/Modal/ModalBase.cs
src/dashboard/Synapse.Dashboard/Features/V1WorkflowInstanceCollectionState.cs
src/dashboard/Synapse.Dashboard/Features/WorkflowInstances/WorkflowInstanceLogs/WorkflowInstanceLogs.razor
src/dashboard/Synapse.Dashboard/Pages/Workflows/View.razor

Adds buttons to both delete and archive workflow instances

Add buttons to both delete and archive workflow instances

---

src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/WorkflowGraphBuilder.cs

Fixed infinite loop in the graph when pointing to an existing state

Fix recursive workflow display

---

src/dashboard/Synapse.Dashboard/Features/WorkflowInstances/WorkflowInstanceToolbar/WorkflowInstanceToolbar.razor
src/dashboard/Synapse.Dashboard/Pages/Workflows/View.razor

Changed margin of "instance actions" buttons

Updated buttons spacing [skip hint]

---

src/dashboard/Synapse.Dashboard/Features/WorkflowInstances/WorkflowInstanceLogs/WorkflowInstanceLogs.razor

Minor style-related fixes to the WorkflowInstanceLogs component

Minor style-related fixes to the WorkflowInstanceLogs component

---

src/core/Synapse.Application/Commands/WorkflowInstances/v1/V1CreateWorkflowInstanceCommand.cs
src/core/Synapse.Application/Commands/Workflows/v1/V1CreateWorkflowCommand.cs
src/core/Synapse.Application/Events/Domain/v1/V1OperationalReportDomainEventHandler.cs
src/dashboard/Synapse.Dashboard/Pages/Index.razor

Allows starting workflows with no version specified, as required by subflows

Allows starting workflows with no version specified, as required by subflows

---

src/core/Synapse.Application/Commands/WorkflowInstances/v1/V1ArchiveWorkflowInstanceCommand.cs
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj

Updates the Serverless Workflow SDK to version 0.8.1.6

Updated the Serverless Workflow SDK to version 0.8.1.6

---

src/apis/management/Synapse.Apis.Management.Http/Controllers/V1WorkflowsController.cs
src/apps/Synapse.Server/Properties/launchSettings.json
src/core/Synapse.Application/Queries/WorkflowActivities/V1GetWorkflowActivitiesQuery.cs
src/core/Synapse.Application/Services/WorkflowScheduler.cs
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/MongoDBRepositoryPlugin.cs
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Services/DynamicObjectSerializer.cs
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Services/DynamicSerializer.cs
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Services/OneOfSerializer.cs

Fixes BSON serialization issues

Fixes BSON serialization

---

deployment/kubernetes/eventstore+mongo.yaml
deployment/kubernetes/stand-alone.yaml
src/runtime/Synapse.Runtime.Kubernetes/Services/KubernetesProcess.cs

**What this PR does / why we need it**: Fixes #151 

Fix kubernetes collect runtime logs

---

src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs

Added evaluation of expressions specified as an OpenAPI function operation

Evaluate OpenAPI function definition operation

---

src/dashboard/Synapse.Dashboard/Extensions/JSchemaExtensions.cs
src/dashboard/Synapse.Dashboard/Features/Shared/JsonForm/JsonForm.razor
src/dashboard/Synapse.Dashboard/Features/Shared/JsonForm/JsonFormProperty.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowToolbar/WorkflowToolbar.razor

Fixed the dashboard's `JsonForm` component, used when rendering the input data form (if schema has been supplied) used to start a new workflow instance

Fixed the dashboard's JsonForm component

---

src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Services/DynamicObjectSerializer.cs

Fixes the resolution of OpenAPI parameters located in-body

Fixed the resolution of OpenAPI parameters located in-body

---

src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs

Fixes the OpenApiFunctionProcessor by double-checking the operation url and its components for runtime expressions

Fixed the OpenApiFunctionProcessor by double-checking the operation url and its components for runtime expressions

---

src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj

Adds missing GeneratePackageOnBuild tag to API client projects and to the Integration project

Added missing GeneratePackageOnBuild tag to API client projects and to the Integration project

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj

Adds nuget package support for API core libraries

Added nuget package support for API core libraries

---

src/apps/Synapse.Cli/Commands/WorkflowInstances/CancelWorkflowInstanceCommand.cs
src/apps/Synapse.Cli/Commands/WorkflowInstances/ResumeWorkflowInstanceCommand.cs
src/apps/Synapse.Cli/Commands/WorkflowInstances/SuspendWorkflowInstanceCommand.cs
src/apps/Synapse.Worker/Services/FileBasedSecretManager.cs
src/apps/Synapse.Worker/Services/IntegrationEventBus.cs
src/apps/Synapse.Worker/Services/Processors/AsyncFunctionProcessor.cs
src/apps/Synapse.Worker/Services/Processors/ConsumeEventProcessor.cs
src/apps/Synapse.Worker/Services/Processors/GraphQLFunctionProcessor.cs
src/apps/Synapse.Worker/Services/Processors/ODataFunctionProcessor.cs
src/apps/Synapse.Worker/Services/Processors/ProduceEventProcessor.cs
src/apps/Synapse.Worker/Services/Processors/SleepStateProcessor.cs
src/apps/Synapse.Worker/Services/Processors/SwitchStateProcessor.cs
src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs
src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs
src/apps/Synapse.Worker/Services/WorkflowFacade.cs
src/apps/Synapse.Worker/Services/WorkflowRuntime.cs
src/apps/Synapse.Worker/Services/WorkflowRuntimeContext.cs
src/core/Synapse.Application/Extensions/IPluginManagerExtensions.cs
src/core/Synapse.Application/Extensions/SwitchStateExtensions.cs
src/dashboard/Synapse.Dashboard/Extensions/IQueryableExtensions.cs
src/dashboard/Synapse.Dashboard/Extensions/PropertyInfoExtensions.cs

Fixes comments and other warnings

Fixed comments and other warnings

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

Includes fix to https://github.com/serverlessworkflow/sdk-net/issues/40
Updates packages to latest version, thus applying fix to https://github.com/serverlessworkflow/sdk-net/issues/40

Updated packages to latest version

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/MongoDBRepositoryPlugin.cs
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Services/DynamicArraySerializer.cs
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Services/DynamicSerializer.cs
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

- Fixed the DynamicSerializer by adding, registering and using a new DynamicArraySerializer
- Updated solution packages

Fixed the DynamicSerializer by adding, registering and using a new DynamicArraySerializer

---

src/apps/Synapse.Worker/Services/Processors/ForEachStateProcessor.cs
src/apps/Synapse.Worker/Services/Processors/IterationProcessor.cs
src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs

- Fixes the IterationStateProcessor which was not properly merging the output collection, if any, back into the state data
- Fixes the ForEachStateProcessor which was outputting the iteration parameter, which is now deleted from the state data
- Fixes the OpenApiFunctionProcessor, which was not removing espace characters inherited from JSON when iterating through expression matches

Fixed the ForEach state, which was not properly outputing data

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Updated solution version

---

README.md

Fixed README file's documentation links

Fixes README file's documentation links

---

src/dashboard/Synapse.Dashboard/Extensions/GraphExtensions.cs

Handled iteration activities in graph

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Updates solution version to 0.1.16

Updated solution version to 0.1.16

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

Updated Neuroglia Framework packages to latest version, thus fixing casing issues with Newtonsoft-based serialization of Dynamics

Fixed casing issues with Newtonsoft-based serialization of Dynamics

---

src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj

- Fixes the EventStateTriggerProcessor, which was not preventing against null or empty trigger actions and was therefore throwing
- Fixes the EventStateTriggerProcessor to properly filter consume events before resuming the flow

Fixed the EventStateTriggerProcessor, which was not preventing against null or empty trigger actions and was therefore throwing

---

src/dashboard/Synapse.Dashboard/Extensions/GraphExtensions.cs
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/WorkflowGraphBuilder.cs

Handled display of event triggers with no action in the graph

---

src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Services/DynamicSerializer.cs

Fixes the DynamicSerializer to handle proper deserialization of DynamicValues

Fixed the DynamicSerializer to handle proper deserialization of DynamicValues

---

src/dashboard/Synapse.Dashboard/Extensions/GraphExtensions.cs

Handled consume event in graph extension

---

src/core/Synapse.Integration/Models/v1/V1Event.cs

Fixes the V1Event model by converting Dynamic values to their raw representation when setting extensions attributes during conversion to CloudEvent

Fixed the V1Event model by converting Dynamic values to their raw representation when setting extensions attributes during conversion to CloudEvent

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/plugin.json
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/plugin.json
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Updated solution to 0.1.19

---

src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/WorkflowGraphBuilder.cs

Fixed the UI, drawing missing edge between default case node and the next state node

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Models/v1/V1EventFilter.cs
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Models/v1/V1EventFilter.cs
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/plugin.json
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/plugin.json
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Fixed the V1EventFilter domain model to make proper use of the Regex.IsMatch method when filtering cloud events

Fixed the V1EventFilter domain model to make proper use of the Regex.IsMatch method when filtering cloud events

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

- Updates the Neuroglia.Serialization.Dynamic package to latest version, thus resolving a bug forbidding the mapping of a DynamicArray to a Dictionary

Updated the Neuroglia.Serialization.Dynamic package to latest version, thus resolving a bug forbidding the mapping of a DynamicArray to a Dictionary

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/OAuth2Token.cs
src/apps/Synapse.Worker/Services/OAuth2TokenManager.cs
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/core/Synapse.Integration/UriHelper.cs
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

Fixes the OAuth2TokenManager to discover the open-id configuration endpoint, thus dynamically resolving token endpoint

Fixed the OAuth2TokenManager to discover the open-id configuration endpoint, thus dynamically resolving token endpoint

---

src/core/Synapse.Application/Services/WorkflowDefinitionFileMonitor.cs

Fixes the WorkflowDefinitionFileMonitor to support live definition file edition

Fixed the WorkflowDefinitionFileMonitor to support live definition file edition

---

src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/WorkflowGraphBuilder.cs

Fixed the UI by taking foreach state mode into account when drawing action nodes.

---

src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/DragAndDropNodeBehavior.cs
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj

Updates Neuroglia.Data.Expressions.JQ package, thus fixing a bug due to a typo when invoking JQ with long expressions and/or input on Linux

Updated Neuroglia.Data.Expressions.JQ package, thus fixing a bug due to a typo when invoking JQ with long expressions and/or input on Linux

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/DragAndDropNodeBehavior.cs
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

Updated to Neuroglia Framework v2.0.1.75

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/plugin.json
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/plugin.json
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Updated solution to v0.1.24

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/plugin.json
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/plugin.json
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Updates solution packages to latest version, thus fixing a Protobuf deserialization bug

Updated solution packages to latest version, thus fixing a Protobuf deserialization bug

---

src/dashboard/Synapse.Dashboard/Pages/Workflows/List.razor

Fixed the workflows list in the UI, actually sorting by version

---

src/apis/management/Synapse.Apis.Management.Http/Controllers/V1WorkflowActivitiesController.cs
src/apis/management/Synapse.Apis.Management.Http/Controllers/V1WorkflowInstancesController.cs
src/apis/management/Synapse.Apis.Management.Http/Extensions/ISynapseApplicationBuilderExtensions.cs
src/apis/management/Synapse.Apis.Management.Http/Services/ODataSearchBinder.cs

- Added ODATA search support for V1Workflows, V1WorkflowInstances, V1WorkflowActivities and V1Correlations
- Added a new controller to manage V1WorkflowActivities

Added ODATA search support for V1Workflows, V1WorkflowInstances, V1WorkflowActivities and V1Correlations

---

src/apps/Synapse.Worker/Services/WorkflowRuntime.cs

Fixes the WorkflowRuntime by renaming ConditionType enum to SwitchCaseOutcomeType

Fixed the WorkflowRuntime by renaming ConditionType enum to SwitchCaseOutcomeType

---

src/apps/Synapse.Worker/Services/WorkflowRuntime.cs
src/apps/Synapse.Worker/Services/WorkflowRuntimeContext.cs

Fixes the WorkflowRuntimeContext by updating the Regex it uses to match expression functions. It now accepts snake and kebab cased names.

Fixed the WorkflowRuntimeContext by updating the Regex it uses to match expression functions. It now accepts snake and kebab cased names.

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/plugin.json
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/plugin.json
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Fixed solution version

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/plugin.json
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/plugin.json
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Updates the solution version to 0.1.26

Updated the solution version to 0.1.26

---

src/core/Synapse.Integration/Models/v1/V1ApplicationInfo.cs

Added data contract/members on application info to prevent marshalling errors

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/plugin.json
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/plugin.json
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Updated projects to version to 0.1.27

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/EventNodeTemplate.razor
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/SleepNodeTemplate.razor
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/StateNodeTemplate.razor
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/WorkflowGraphBuilder.cs
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/WorkflowNodeTemplate.razor
src/dashboard/Synapse.Dashboard/Pages/Workflows/Editor/Editor.razor
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

Update to Neuroglia.Framework 2.0.1.88

---

.github/workflows/auto-version.yml

This commit will not affect the version of the published code. See [Commit Hints](https://github.com/cbcrouse/Versioning.NET/wiki/Commit-Hints).
* Adds a new workflow which triggers on changes from the `main` branch that will result in the project version being incremented.
* The URL for the repository might not be entirely correct, please review the tokens and username values. I tried to grab values from the [publish workflow](https://github.com/serverlessworkflow/synapse/blob/main/.github/workflows/publish.yml).
Due to the existing workflow that triggers on release, I did not add any additional workflows. If you decide …

ci(Workflows): New versioning workflow [skip hint]

---

GOVERNANCE.md
Synapse.sln

Updating the GOVERNANCE.md file by fixing case issues with the contributing guide link

Updating the GOVERNANCE.md file by fixing case issues with the contributing guide link

---

.github/workflows/ci-pipeline.yml
.github/workflows/publish.yml

Fixed publish CI pipeline

---

.github/workflows/ci-pipeline.yml
.github/workflows/publish.yml

Fixed typo in CI pipeline

---

.github/workflows/publish.yml

Rolled back publish CI pipeline to a working version

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

Updates Neuroglia Framework packages to latest version, thus resolving a critical expression evaluation issue introduced by previous release

Updated Neuroglia Framework packages to latest version, thus resolving a critical expression evaluation issue introduced by previous release

---

src/runtime/Synapse.Runtime.Docker/Services/DockerRuntime.cs

Fixes the DockerRuntime to only pull image with specific tag instead of all available tags

Fixed the DockerRuntime to only pull image with specific tag instead of all available tags

---

README.md

Improves the readme attractivity

Added synapse gif as dashboard illustration in the readme

---

src/apis/management/Synapse.Apis.Management.Http/Extensions/ISynapseApplicationBuilderExtensions.cs
src/core/Synapse.Application/Commands/Schedules/v1/V1CompleteScheduleOccurenceCommand.cs
src/core/Synapse.Application/Services/EdmModelBuilder.cs
src/core/Synapse.Application/Services/ODataSearchBinder.cs
src/core/Synapse.Integration/Commands/Generic/v1/Generated/V1PatchCommand.cs
src/core/Synapse.Integration/Commands/Schedules/v1/Generated/V1CompleteScheduleOccurenceCommand.cs
src/core/Synapse.Integration/Models/v1/V1PluginInfo.cs
src/dashboard/Synapse.Dashboard/Pages/Schedules/List/Actions.cs
src/dashboard/Synapse.Dashboard/Pages/Schedules/List/View.razor

- Fixes the EdmModelBuilder to configure the V1Schedule ent…ity set
- Fixes the ODataSearchBinder to allow V1Schedule searches

Adds OData support for `V1Schedules`

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

Updated Neuroglia Framework version to handle JQ expressions with string interpolation

Updated to latest version of the Neuroglia Framework to handle JQ expressions with string interpolation

---

src/apps/Synapse.Cli/Commands/Systems/Installs/NativeInstallCommand.cs
src/runtime/Synapse.Runtime.Native/Services/NativeRuntime.cs

Fixed the URL to automatically download releases in native mode

---

src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Server/appsettings.json
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Services/PluginBasedRepositoryFactory.cs
src/core/Synapse.Application/Services/WorkflowDefinitionFileMonitor.cs
src/core/Synapse.Application/Services/WorkflowProcessManager.cs
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/EventStoreRepositoryPlugin.cs
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

- Fixes Neuroglia package reference, thus fixing a critical EventStore bug related to snapshot serialization
- Fixes the WorkflowProcessManager to enqueue log processing and catch/handle/retry on OptimisticConcurrencyExceptions
Fixes #313

Fixed Neuroglia package reference, thus fixing a critical EventStore bug related to snapshot serialization

---

src/apps/Synapse.Server/appsettings.json
src/apps/Synapse.Worker/Services/Processors/AsyncFunctionProcessor.cs
src/core/Synapse.Application/Extensions/V1EventExtensions.cs

- Fixed the V1EventExtensions, which were not checking the event's extensions for null before enumerating
- Fixed the AsyncFunctionProcessor to properly filter the trigger event's data

Fixed production of cloud events

---

src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure.Containers.Docker/Synapse.Core.Infrastructure.Containers.Docker.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Synapse.Runner.csproj
src/runtime/Synapse.Runtime.Abstractions/Synapse.Runtime.Abstractions.csproj
src/runtime/Synapse.Runtime.Containerized/Synapse.Runtime.Containerized.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Fixes versioning of all projects in solution

Fixed versioning of all projects in solution

---

src/core/Synapse.Core.Infrastructure.Containers.Docker/DockerContainerPlatform.cs

Fixes the DockerContainerPlatform to pull images by tag instead of always fetching latest
Closes #383

Fix the DockerContainerPlatform to pull images by tag

---

src/api/Synapse.Api.Http/Extensions/IServiceCollectionExtensions.cs

- Adds a new security scheme and requirement to Swagger, allowing users to authenticate in the UI using static tokens
Closes #384

Add a static token security scheme and requirement to Swagger

---

src/api/Synapse.Api.Server/appsettings.Development.json
src/core/Synapse.Core/Annotations/CloudEventAttribute.cs
src/core/Synapse.Core/Events/Tasks/RetryingTaskEventV1.cs
src/core/Synapse.Core/Events/Tasks/TaskCancelledEventV1.cs
src/core/Synapse.Core/Events/Tasks/TaskCompletedEventV1.cs
src/core/Synapse.Core/Events/Tasks/TaskCreatedEventV1.cs
src/core/Synapse.Core/Events/Tasks/TaskEndedEventV1.cs
src/core/Synapse.Core/Events/Tasks/TaskFaultedEventV1.cs
src/core/Synapse.Core/Events/Tasks/TaskResumedEventV1.cs
src/core/Synapse.Core/Events/Tasks/TaskSkippedEventV1.cs
src/core/Synapse.Core/Events/Tasks/TaskStartedEventV1.cs
src/core/Synapse.Core/Events/Tasks/TaskSuspendedEventV1.cs
src/core/Synapse.Core/Events/Workflows/WorkflowCancelledEventV1.cs
src/core/Synapse.Core/Events/Workflows/WorkflowCompletedEventV1.cs
src/core/Synapse.Core/Events/Workflows/WorkflowCorrelationCompletedEventV1.cs
src/core/Synapse.Core/Events/Workflows/WorkflowCorrelationStartedEventV1.cs
src/core/Synapse.Core/Events/Workflows/WorkflowEndedEventV1.cs
src/core/Synapse.Core/Events/Workflows/WorkflowFaultedEventV1.cs
src/core/Synapse.Core/Events/Workflows/WorkflowResumedEventV1.cs
src/core/Synapse.Core/Events/Workflows/WorkflowStartedEventV1.cs
src/core/Synapse.Core/Events/Workflows/WorkflowSuspendedEventV1.cs
src/core/Synapse.Core/SynapseDefaults.cs
src/runner/Synapse.Runner/Configuration/RunnerCloudEventOptions.cs
src/runner/Synapse.Runner/Configuration/RunnerOptions.cs
src/runner/Synapse.Runner/Services/WorkflowExecutionContext.cs

- Updates the WorkflowExecutionContext to publish cloud events after handling each and every workflow and task operations
Closes #381

Updated the WorkflowExecutionContext to publish cloud events after handling each and every workflow and task operations

---

src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/ResourceController.cs
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/dashboard/Synapse.Dashboard/Services/WorkflowGraphBuilder.cs
tests/Synapse.IntegrationTests/Synapse.IntegrationTests.csproj
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

- Updates ServerlessWorkflow packages to latest version thus resolving ASP.NET Core validation bugs related to non-nullable authentication properties when dealing with secret-based authentications

Update ServerlessWorkflow packages to latest version

---

src/core/Synapse.Core/Extensions/WorkflowDefinitionExtensions.cs
src/dashboard/Synapse.Dashboard/Services/WorkflowGraphBuilder.cs

Handled conditional tasks in the dashboard graph

---

src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure.Containers.Docker/Synapse.Core.Infrastructure.Containers.Docker.csproj
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/Synapse.Core.Infrastructure.Containers.Kubernetes.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Synapse.Runner.csproj
src/runtime/Synapse.Runtime.Abstractions/Synapse.Runtime.Abstractions.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

- Updates the version suffix for all projects

Updated the version suffix for all projects

---

.github/workflows/ci-pipeline.yml
src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure.Containers.Docker/Synapse.Core.Infrastructure.Containers.Docker.csproj
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/Synapse.Core.Infrastructure.Containers.Kubernetes.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Synapse.Runner.csproj
src/runtime/Synapse.Runtime.Abstractions/Synapse.Runtime.Abstractions.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Rolled back to v1.0.0-alpha

---

src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/State.cs

Fixes the DSL version used by newly created workflows

Fix the DSL version used by newly created workflows

---

src/dashboard/Synapse.Dashboard/Program.cs

- Fixes the default global JsonSerializer options by enforcing indentation

Fixed the default global JsonSerializer options by enforcing indentation

---

src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure.Containers.Docker/Synapse.Core.Infrastructure.Containers.Docker.csproj
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/Synapse.Core.Infrastructure.Containers.Kubernetes.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/dashboard/Synapse.Dashboard/Components/TaskInstanceDetails/TaskInstanceDetails.razor
src/dashboard/Synapse.Dashboard/Components/WorkflowInstanceDetails/TaskInstanceRow.razor
src/dashboard/Synapse.Dashboard/Components/WorkflowInstanceDetails/WorkflowInstanceDetails.razor
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Synapse.Runner.csproj
src/runtime/Synapse.Runtime.Abstractions/Synapse.Runtime.Abstractions.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Improved task hierarchy navigation using a "tree view" in the Dashboard.

Improved task hierarchy navigation using a "tree view" in the Dashboard

---

src/api/Synapse.Api.Http/ClusterResourceController.cs
src/api/Synapse.Api.Http/NamespacedResourceController.cs
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/operator/Synapse.Operator/Services/WorkflowController.cs
src/operator/Synapse.Operator/Services/WorkflowInstanceController.cs
src/operator/Synapse.Operator/appsettings.Development.json
src/runner/Synapse.Runner/Services/Executors/TryTaskExecutor.cs
src/runner/Synapse.Runner/Synapse.Runner.csproj
tests/Synapse.IntegrationTests/Synapse.IntegrationTests.csproj
tests/Synapse.UnitTests/Cases/Runtime/NativeRuntimeTests.cs
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

- Fixes the `TryTaskExecutor` by updating context data after running nested try and catch tasks
- Fixes the cluster and namespaced resource controllers to handle cancellation-related exceptions when enumerating SSE events
- Fixes the `WorkflowController` not to throw when version compared version lists have no diff patch operations
- Fixes the `WorkflowInstanceController` to delete all related documents
- Updates solution packages, thus resolving a bug in the dashboard when rendering a workflow's graph

Fix try catch context handling

---

src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/dashboard/Synapse.Dashboard/Components/WorkflowDiagram/WorkflowDiagram.razor
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/runner/Synapse.Runner/Synapse.Runner.csproj
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

Added a feature to center the graph to a clicked node in the dashboard.
Closes #464 

Add center to clicked node feature on the Dashboard's graph

---

src/operator/Synapse.Operator/Services/WorkflowInstanceController.cs

- Fixes the `WorkflowInstanceController` to ignore instances of unselected workflows
Fixes #527

Fixed the `WorkflowInstanceController` to ignore instances of unselected workflows

---

src/dashboard/Synapse.Dashboard/Layout/MainLayout.razor
src/dashboard/Synapse.Dashboard/Pages/Correlators/List/View.razor

Adds a link to the (preexisting) namespace management view.
Closes #513

Added namespace management view in the Dashboard
