src/runtime/Synapse.Runtime.Native/Services/NativeRuntimeHost.cs

Fixed typo in the NativeRuntimeHost which resulted in invalid worker download url

Fixed invalid download worker url in native mode on OSX

---

src/apps/Synapse.Worker/Configuration/ApplicationOptions.cs
src/apps/Synapse.Worker/Program.cs
src/core/Synapse.Application/Configuration/SynapseApplicationBuilder.cs
src/core/Synapse.Application/Configuration/SynapseApplicationOptions.cs
src/core/Synapse.Integration/EnvironmentVariables.cs
src/runtime/Synapse.Runtime.Docker/Services/DockerRuntimeHost.cs

- Fixes the way the server's container id was retrieved, which seemed to not work as expected on some systems
- Added options to configure the skipping of certificate validation, which was required in some specific, exotic use-cases

Fix container id retrieval and allow skipping certificate validation

---

src/core/Synapse.Application/Mapping/Configuration/V1EventMappingConfiguration.cs

Fixed the V1EventMappingConfiguration by setting the mapping for the SpecVersion property when converting from a CloudEvent. 
Without that, the SpecVersion would always be equal to `CloudNative.CloudEvents.CloudEventsSpecVersion`

Fixed the V1EventMappingConfiguration by setting the mapping for the SpecVersion property when converting from a CloudEvent

---

src/apps/Synapse.Server/Program.cs
src/apps/Synapse.Server/Properties/launchSettings.json
src/dashboard/Synapse.Dashboard/Program.cs
src/dashboard/Synapse.Dashboard/Properties/launchSettings.json

- Use builder.HostEnvironment.BaseAddress for configuring api clients, thus avoiding additional configuration needs as well as CORS settings
- Configures the server to allow live-reload and debugging of the Dashboard

Enable dashboard live reload and debugging

---

src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowToolbar/WorkflowToolbar.razor

Prevented the value of the input in the 'start workflow' modal to be overriden each time `OnParametersSetAsync` was called.
Closes serverlessworkflow#76

fix(Dashboard): Prevented to reset start input value with each OnParametersSetAsync

---

src/dashboard/Synapse.Dashboard/Extensions/GraphExtensions.cs

Prevented "NotSupportedException" when trying to find a graph node for an activity type that is not represented

---

src/apps/Synapse.Worker/Services/WorkflowRuntimeContext.cs

Fixed the WorkflowRuntimeContext by renaming the CONTEXT runtime expression variable into `WORKFLOW`, as defined by the SW spec

Fixed the WorkflowRuntimeContext by renaming the CONTEXT runtime expression variable into `WORKFLOW`

---

src/dashboard/Synapse.Dashboard/Pages/Workflows/View.razor

Only displays instances for the active workflow definition in the workflow view.

fix(Dashboard): Display active workflow instances only in workflow view

---

src/apps/Synapse.Worker/Extensions/HttpClientExtensions.cs
src/core/Synapse.Application/Events/Domain/v1/V1WorkflowActivityDomainEventHandler.cs
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Services/DynamicObjectSerializer.cs

- Fixes the V1WorkflowActivityDomainEventHandler to properly update parent V1WorkflowInstances upon change
- Fixes the DynamicObjectSerializer by using the RelaxedExtendedJson JsonOutputMode when converting a BSON document to JSON

Fixed the V1WorkflowActivityDomainEventHandler to properly update parent V1WorkflowInstances upon change

---

src/apis/management/Synapse.Apis.Management.Core/Synapse.Apis.Management.Core.csproj
src/apis/management/Synapse.Apis.Management.Grpc.Client/Synapse.Apis.Management.Grpc.Client.csproj
src/apis/management/Synapse.Apis.Management.Grpc/Synapse.Apis.Management.Grpc.csproj
src/apis/management/Synapse.Apis.Management.Http.Client/Synapse.Apis.Management.Http.Client.csproj
src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apis/management/Synapse.Apis.Management.Ipc.Client/Synapse.Apis.Management.Ipc.Client.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.Core/Synapse.Apis.Monitoring.Core.csproj
src/apis/monitoring/Synapse.Apis.Monitoring.WebSocket/Synapse.Apis.Monitoring.WebSocket.csproj
src/apis/runtime/Synapse.Apis.Runtime.Core/Synapse.Apis.Runtime.Core.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Synapse.Apis.Runtime.Grpc.Client.csproj
src/apis/runtime/Synapse.Apis.Runtime.Grpc/Synapse.Apis.Runtime.Grpc.csproj
src/apis/runtime/Synapse.Apis.Runtime.Ipc.Client/Synapse.Apis.Runtime.Ipc.Client.csproj
src/apps/Synapse.Cli/Synapse.Cli.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Configuration/KubernetesRuntimeOptions.cs
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Fixes the default Kubernetes runtime options to always pull the worker image of the current assembly version, instead of latest if not present

Fixed the default Kubernetes runtime options to always pull the worker image of the current assembly version, instead of latest if not present

---

src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs

Fixes the OpenApiFunctionProcessor by including path-level parameters when initializing the processor

Fixed the OpenApiFunctionProcessor by including path-level parameters when initializing the processor

---

.gitignore
src/apps/Synapse.Worker/Program.cs
src/apps/Synapse.Worker/Services/FileBasedSecretManager.cs
src/core/Synapse.Application/Commands/WorkflowInstances/v1/V1ResumeWorkflowInstanceCommand.cs
src/core/Synapse.Application/Commands/WorkflowInstances/v1/V1StartWorkflowInstanceCommand.cs
src/core/Synapse.Application/Services/WorkflowProcessManager.cs
src/core/Synapse.Application/Services/WorkflowRuntimeHostBase.cs
src/core/Synapse.Infrastructure/Services/IWorkflowProcessManager.cs
src/core/Synapse.Infrastructure/Services/IWorkflowRuntime.cs
src/runtime/Synapse.Runtime.Docker/Services/DockerRuntimeHost.cs
src/runtime/Synapse.Runtime.Kubernetes/Services/KubernetesRuntimeHost.cs
src/runtime/Synapse.Runtime.Native/Services/NativeRuntimeHost.cs

Updated the IWorkflowProcessManager and IWorkflowRuntime interfaces to accept a V1Workflow argument when creating a new process, thus enabling implementations to analyze and mount required secrets, if anywRuntime interfaces to accept a V1Workflow argument when creating a new process, thus enabling implementations to analyze and mount required secrets, if any

Updated the IWorkflowProcessManager and IWorkflowRuntime interfaces to accept a V1Workflow argument when creating a new process

---

src/core/Synapse.Domain/Models/v1/V1Correlation.cs
src/core/Synapse.Integration/Models/v1/Generated/V1Correlation.cs
src/core/Synapse.Integration/Models/v1/V1Correlation.cs

Fixes the V1Correlation by properly annotating ignored properties, thus avoiding serialization issues

Fixed the V1Correlation by properly annotating ignored properties, thus avoiding serialization issues

---

src/core/Synapse.Domain/Models/v1/V1EventFilter.cs
src/core/Synapse.Integration/Models/v1/V1EventFilter.cs
src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/WorkflowGraphBuilder.cs

Fixes the V1EventFilter and its DTO to properly filter events in order to prevent correlating unrelated instances that define the same condition

Fixed the V1EventFilter and its DTO to properly filter events in order to prevent correlating unrelated instances that define the same condition

---

src/apis/management/Synapse.Apis.Management.Http/Controllers/V1CorrelationsController.cs
src/apis/management/Synapse.Apis.Management.Http/Controllers/V1WorkflowActivitiesController.cs
src/apis/management/Synapse.Apis.Management.Http/Controllers/V1WorkflowInstancesController.cs
src/apis/management/Synapse.Apis.Management.Http/Controllers/V1WorkflowsController.cs
src/apis/management/Synapse.Apis.Management.Http/Extensions/ISynapseApplicationBuilderExtensions.cs
src/apis/management/Synapse.Apis.Management.Http/Services/ODataSearchBinder.cs
src/core/Synapse.Application/Queries/Generic/V1FilterQuery.cs

Fixes all HTTP Management API controllers to support the '$search' ODATA clause by manually filtering based on bound search expression

Fixed all HTTP Management API controllers to support the '$search' ODATA clause by manually filtering based on bound search expression

---

src/core/Synapse.Application/Queries/Workflows/V1GetWorkflowByIdQuery.cs
src/core/Synapse.Application/Synapse.Application.csproj

Fixed the V1GetWorkflowByIdQueryHandler by sorting workflows by SemVersion rather than by string

Fixed the V1GetWorkflowByIdQueryHandler by sorting workflows by SemVersion rather than by string

---

src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs

Fixes the OpenApiFunctionProcessor, which was trying to build the function's arguments, even though the function reference did not define any

Fixed the OpenApiFunctionProcessor, which was trying to build the function's arguments, even though the function reference did not define any

---

.github/workflows/versioning.yml

Recently, Versioning.NET tool received a breaking change update and since this pipeline does not target a specific version, this will avoid the pipeline breaking in the future by accounting for the breaking change.

ci(Versioning): Update command due to recent breaking changes to Versioning.NET

---

src/dashboard/Synapse.Dashboard/Features/Shared/Jq/InputJqExpression.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/EventCaseEditor.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/JqExpressionEditor.razor

Trimmed `${ }` from jq expressions input in jq editor

fix(Dashboard): trimmed jq expression in editor

---

src/core/Synapse.Domain/Models/v1/V1CorrelationContext.cs
src/core/Synapse.Domain/Models/v1/V1Event.cs
src/core/Synapse.Domain/Models/v1/V1EventFilter.cs
src/core/Synapse.Integration/Models/v1/V1EventFilter.cs

- Fixes the V1CorrelationContext, V1Event and V1EventFilter to support regular expressions when evaluating contextual mapping values
- Fixes the V1EventFilter to support regular expressions when evaluating contextual mapping values

Add regular expressions support  when evaluating event mapping values

---

src/dashboard/Synapse.Dashboard/Features/Shared/WorkflowDiagram/FunctionRefNodeViewModel.cs

Used the action name if available instead of the function name in the graph.

Display action name instead of function name in the graph

---

src/apis/management/Synapse.Apis.Management.Http/Synapse.Apis.Management.Http.csproj
src/apps/Synapse.Server/Synapse.Server.csproj
src/apps/Synapse.Worker/Extensions/IWorkflowRuntimeContextExtensions.cs
src/apps/Synapse.Worker/Services/Processors/InjectStateProcessor.cs
src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs
src/apps/Synapse.Worker/Synapse.Worker.csproj
src/core/Synapse.Application/Synapse.Application.csproj
src/core/Synapse.Domain/Synapse.Domain.csproj
src/core/Synapse.Infrastructure/Synapse.Infrastructure.csproj
src/core/Synapse.Integration/Synapse.Integration.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj
src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj

- Updates Neuroglia packages for solution, thus resolving a bug with command line escaping in Unix when evaluating inline escaped json
- Fixes the InjectStateProcessor to evaluate the defined data before injecting it into the state's
- Fixes the OpenApiFunctionProcessor to use the EvaluateObjectAsync IWorkflowRuntimeContext extension when building object, instead of using its own routine

Updated Neuroglia packages for solution, thus resolving a bug with command line escaping in Unix when evaluating inline escaped json

---

src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs

- Fixes the OpenApiFunctionProcessor which was incorrectly quoting function parameters upon evaluation (`."param"` replaced byf `.["param"]`)

Fixed the OpenApiFunctionProcessor which was incorrectly quoting function parameters upon evaluation (`."param"` replaced byf `.["param"]`)

---

src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/StateEditor.razor

When editing the name of a state in the editor, the referring state transition wasn't updated, leading to a broken definition. This PR intend to update those broken references.

Updating state references (transition/compensation) when its name has been change in the editor

---

src/dashboard/Synapse.Dashboard/Features/Shared/JsonForm/JsonFormProperty.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/ActionEditor.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/EventEditor.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/EventStateTriggerEditor.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/FunctionEditor.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/GrpcOperationSelector.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/ODataEntitySetSelector.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/OpenApiOperationSelector.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/StateEditors/ForEachStateEditor.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/StateEditors/OperationStateEditor.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/StateEditors/ParallelStateEditor.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/WorkflowEditor.razor
src/dashboard/Synapse.Dashboard/Features/Workflows/WorkflowEditor/WorkflowSelector.razor

Continuation of #302, decorated all `select` with the `form-select` instead of `form-control`

Replace select class "form-control" with "form-select"

---

src/core/Synapse.Integration/Serialization/Converters/FilteredExpandoObjectConverter.cs

Fixes casing issues during serialization of Dynamic values. The casing of dynamic value property names should now be preserved.
Fixes #192

Fixed casing issues during serialization of Dynamic values. The casing of dynamic value property names should now be preserved.

---

src/apps/Synapse.Worker/Extensions/IWorkflowRuntimeContextExtensions.cs
src/apps/Synapse.Worker/Services/Processors/ODataFunctionProcessor.cs

Fixed the ODataFunctionProcessor to properly evaluate both operation uri and arguments before performing the ODATA call

Fixed the ODataFunctionProcessor to properly evaluate both operation uri and arguments before performing the ODATA call

---

src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs

Fixes the OpenApiFunctionProcessor, which was failling unexpectedly when returned contentless responses, or when the response's content type was not set

Fixed the OpenApiFunctionProcessor, which was failling unexpectedly when returned contentless responses

---

src/dashboard/Synapse.Dashboard/wwwroot/lib/js-yaml/package.json

Removed `gh-pages` from js-yaml library package.json to fix https://github.com/serverlessworkflow/synapse/security/dependabot/2

Removed unused and unsafe dependency

---

deployments/docker-compose/docker-compose.build.yml
deployments/docker-compose/docker-compose.yml
src/api/Synapse.Api.Server/Program.cs
src/core/Synapse.Core.Infrastructure/Services/OAuth2TokenManager.cs

Fixed the OAuth2TokenManager by disabling HTTPS requirements when performing OIDC discovery requests
Closes #379

Fixed the OAuth2TokenManager by disabling HTTPS requirements when performing OIDC discovery requests

---

src/core/Synapse.Core/Resources/RunnerDefinition.cs

- Fixes the Operator's RunnerDefinition by making its `Certificates` property optional
Closes #382

Fix the Operator's RunnerDefinition by making its `Certificates` property optional

---

src/api/Synapse.Api.Application/Commands/Resources/CreateResourceCommand.cs
src/api/Synapse.Api.Application/Commands/Resources/Generic/CreateResourceCommand.cs
src/core/Synapse.Core.Infrastructure.Containers.Docker/DockerContainerPlatform.cs
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/KubernetesContainer.cs
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/KubernetesContainerPlatform.cs
src/core/Synapse.Core/Events/Workflows/WorkflowCompletedEventV1.cs
src/core/Synapse.Core/Resources/Document.cs
src/core/Synapse.Core/Resources/NativeRuntimeConfiguration.cs
src/core/Synapse.Core/Resources/TaskInstance.cs
src/core/Synapse.Core/Synapse.Core.csproj
src/core/Synapse.Core/SynapseDefaults.cs
src/correlator/Synapse.Correlator/Services/CorrelationHandler.cs
src/runner/Synapse.Runner/Services/Executors/ContainerProcessExecutor.cs
src/runner/Synapse.Runner/Services/SecretsManager.cs
src/runner/Synapse.Runner/Services/WorkflowExecutionContext.cs
src/runtime/Synapse.Runtime.Docker/Services/DockerRuntime.cs
src/runtime/Synapse.Runtime.Kubernetes/Services/KubernetesRuntime.cs
src/runtime/Synapse.Runtime.Kubernetes/Services/KubernetesWorkflowProcess.cs
src/runtime/Synapse.Runtime.Native/Services/NativeRuntime.cs
tests/Synapse.UnitTests/Cases/Conformance/ConformanceTestsBase.cs
tests/Synapse.UnitTests/Services/MockWorkflowExecutionContextFactory.cs

- Fixes the `WorkflowCompletedEventV1` by adding a new `output` property
- Fixes all runtimes to set both the runner's `NAMESPACE` and `NAME` environment variables
- Fixes all container platforms to name spawned containers after both the runner and their image
- Fixes the ContainerTaskExecutor by removing output truncation when using Kubernetes
- Fixes the KubernetesContainer by fixing the WaitForExit method
- Changed the Nuget package name to Synapse to avoid collision with a package from another company
Closes #396

Fix `WorkflowCompletedEventV1` by adding a new `output` property

---

src/core/Synapse.Core/SynapseDefaults.cs
src/runner/Synapse.Runner/AuthorizationInfo.cs
src/runner/Synapse.Runner/Extensions/HttpClientExtensions.cs
src/runner/Synapse.Runner/Services/Executors/ForTaskExecutor.cs
src/runner/Synapse.Runner/Services/Executors/ForkTaskExecutor.cs
src/runner/Synapse.Runner/Services/Executors/FunctionCallExecutor.cs
src/runner/Synapse.Runner/Services/Executors/HttpCallExecutor.cs
src/runner/Synapse.Runner/Services/Executors/OpenApiCallExecutor.cs
src/runner/Synapse.Runner/Services/ExternalResourceProvider.cs
src/runner/Synapse.Runner/Services/TaskExecutor.cs
src/runner/Synapse.Runner/Services/WorkflowExecutor.cs

- Fixes the AuthorizationInfo to resolve referenced authentication policies defined at top level

Fix the AuthorizationInfo to resolve referenced authentication policies

---

src/runner/Synapse.Runner/Services/TaskExecutor.cs

* Fixes the TaskExecutor to evaluate `export.as` against the task transformed output instead of context data

Fixed the TaskExecutor to evaluate `export.as` against the task transformed output instead of context data

---

src/operator/Synapse.Operator/Program.cs

- Fixes the operator to use IOptionsMonitor instead of IOptions to access the OperatorOptions, thus making sure the proper resource-based configuration

Fixed the operator to use IOptionsMonitor instead of IOptions to access the OperatorOptions

---

src/core/Synapse.Core/Synapse.Core.csproj
src/runner/Synapse.Runner/Services/Executors/OpenApiCallExecutor.cs

- Fixes the `OpenApiCallProcessor` to interpolate and evaluate the endpoint URI te the endpoint URI before performing the request

Fixed the `OpenApiCallProcessor`to interpolate and evaluate the document endpoint URI 

---

src/runner/Synapse.Runner/Services/Executors/HttpCallExecutor.cs
src/runner/Synapse.Runner/Services/Executors/OpenApiCallExecutor.cs

* Fixes the way both the `HttpCallProcessor` and `OpenApiCallProcessor` evaluate endpoint URIs, by retrieving the contextual expression evaluation arguments instead of the task's

Fixed the way both the `HttpCallProcessor` and `OpenApiCallProcessor` evaluate endpoint URIs

---

src/dashboard/Synapse.Dashboard/Components/ResourceEditor/Store.cs

* Fixes the ResourceEditor component's store to properly serialize resources upon initialization, thus resolving casing issues with V1Pod

Fixed the ResourceEditor component's store to properly serialize resources upon initialization

---

src/core/Synapse.Core/WorkflowInstanceStatusPhase.cs
src/correlator/Synapse.Correlator/Services/CorrelationHandler.cs
src/runner/Synapse.Runner/Services/Executors/ContainerProcessExecutor.cs
src/runner/Synapse.Runner/Services/Executors/ExtensionTaskExecutor.cs
src/runner/Synapse.Runner/Services/Executors/GrpcCallExecutor.cs
src/runner/Synapse.Runner/Services/Executors/HttpCallExecutor.cs
src/runner/Synapse.Runner/Services/Executors/SwitchTaskExecutor.cs
src/runner/Synapse.Runner/Services/Executors/WorkflowProcessExecutor.cs
src/runner/Synapse.Runner/Services/TaskExecutor.cs
src/runner/Synapse.Runner/Services/WorkflowExecutionContext.cs

- Implements the WorkflowProcessExecutor
- Fixes all TaskExecutors to log errors

Implemented the WorkflowProcessExecutor

---

src/api/Synapse.Api.Application/Services/CloudEventPublisher.cs
src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure.Containers.Docker/Synapse.Core.Infrastructure.Containers.Docker.csproj
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/Synapse.Core.Infrastructure.Containers.Kubernetes.csproj
src/core/Synapse.Core.Infrastructure/Services/DatabaseInitializer.cs
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/core/Synapse.Core/SynapseDefaults.cs
src/correlator/Synapse.Correlator/Configuration/CloudEventConsumptionOptions.cs
src/correlator/Synapse.Correlator/Configuration/CorrelatorOptions.cs
src/correlator/Synapse.Correlator/Program.cs
src/correlator/Synapse.Correlator/Services/RedisCloudEventIngestor.cs
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Synapse.Runner.csproj
src/runtime/Synapse.Runtime.Abstractions/Synapse.Runtime.Abstractions.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Implements an internal cloud event bus, allowing solution components to correlate internally emitted events
The bus leverages Redis for its implementation. Based on the version of the Redis server in use, the APIs and correlators will either utilize Redis Streams or emulate streaming functionality through Redis Lists.

Publish emitted events on internal bus

---

src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Extensions/TaskDefinitionMapExtensions.cs
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/dashboard/Synapse.Dashboard.StateManagement/Synapse.Dashboard.StateManagement.csproj
src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Details/View.razor
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Services/Executors/OpenApiCallExecutor.cs
src/runner/Synapse.Runner/Synapse.Runner.csproj
tests/Synapse.IntegrationTests/Synapse.IntegrationTests.csproj
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

- Updates solution packages to latest version
- Multiple fixes and improvements

Updated solution packages to latest version

---

src/api/Synapse.Api.Application/Configuration/AuthenticationPolicyOptions.cs
src/api/Synapse.Api.Application/Configuration/JwtBearerAuthenticationOptions.cs
src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Program.cs
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure.Containers.Docker/Synapse.Core.Infrastructure.Containers.Docker.csproj
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/Synapse.Core.Infrastructure.Containers.Kubernetes.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/core/Synapse.Core/SynapseDefaults.cs
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Services/Interfaces/IOAuth2TokenManager.cs
src/runner/Synapse.Runner/Services/OAuth2TokenManager.cs
src/runner/Synapse.Runner/Synapse.Runner.csproj
src/runtime/Synapse.Runtime.Abstractions/Synapse.Runtime.Abstractions.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

- Moves the `IOAuth2TokenManager` and its implementation from the Infrastructure project to the runner's
- Fixes the `OAuth2TokenManager` to not validate access token issuer name
- Addes environment variable based configuration of the API's JwT issuer, its signing key and its name validation
Signed-off-by: Charles d'Avernas <charles.davernas@neuroglia.io>

Fixed the `OAuth2TokenManager` to not validate access token issuer name

---

src/runner/Synapse.Runner/Services/OAuth2TokenManager.cs

- Fixes the OAuth2TokenManager to not validate the OIDC discovery document endpoints

fix(Runner): Fixed the OAuth2TokenManager to not validate the OIDC discovery document endpoints

---

src/dashboard/Synapse.Dashboard/Components/TaskInstanceDetails/TaskInstanceDetails.razor
src/dashboard/Synapse.Dashboard/Components/WorkflowInstanceDetails/TaskInstanceRow.razor
src/dashboard/Synapse.Dashboard/Components/WorkflowInstanceDetails/WorkflowInstanceDetails.razor
src/dashboard/Synapse.Dashboard/Components/WorkflowInstancesList/WorkflowInstancesList.razor
src/dashboard/Synapse.Dashboard/Extensions/DateTimeExtensions.cs
src/dashboard/Synapse.Dashboard/Pages/Correlations/List/View.razor
src/dashboard/Synapse.Dashboard/Pages/Correlators/List/View.razor
src/dashboard/Synapse.Dashboard/Pages/Operators/List/View.razor
src/dashboard/Synapse.Dashboard/Pages/Workflows/List/View.razor

Fixes the format of all date times by properly converting them to local time

Fixed the format of all date times by properly converting them to local time

---

src/runner/Synapse.Runner/Services/Executors/SwitchTaskExecutor.cs

- Fixes the `SwitchTaskExecutor` to not throw when multiple cases match, and to select the first matching case, if any, following declaration order

Fixed the `SwitchTaskExecutor` to not throw when multiple cases match, and to select the first matching case, if any

---

src/runner/Synapse.Runner/Services/WorkflowExecutionContext.cs

- Fixes the `WorkflowExecutionContext` to properly set the status of an ended task, which was being wrongly set to the workflow instance's status

Fixed the `WorkflowExecutionContext` to properly set the status of an ended task

---

src/dashboard/Synapse.Dashboard/Components/DocumentDetails/DocumentDetails.razor
src/dashboard/Synapse.Dashboard/Components/DocumentDetails/Store.cs
src/dashboard/Synapse.Dashboard/Components/MonacoEditor/MonacoEditor.razor
src/dashboard/Synapse.Dashboard/Components/MonacoEditor/MonacoEditorHelper.cs
src/dashboard/Synapse.Dashboard/Components/MonacoEditor/Store.cs
src/dashboard/Synapse.Dashboard/Components/ResourceEditor/ResourceEditor.razor
src/dashboard/Synapse.Dashboard/Pages/Functions/Create/View.razor
src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/State.cs

- Adds buttons to copy the content of the targeted editor to the clipboard.

Added copy to clipboard button to the Dashboard's editors

---

src/runner/Synapse.Runner/Services/Executors/OpenApiCallExecutor.cs

- Fixes the `OpenApiCallExecutor` to evaluate the `operationId` parameter when its value is a runtime expressions

Fixed the `OpenApiCallExecutor` to evaluate the `operationId` parameter when its value is a runtime expressions

---

src/dashboard/Synapse.Dashboard/Components/MonacoEditor/MonacoEditorHelper.cs
src/dashboard/Synapse.Dashboard/Pages/Functions/Create/Store.cs
src/dashboard/Synapse.Dashboard/Services/SpecificationSchemaManager.cs
src/dashboard/Synapse.Dashboard/wwwroot/js/monaco-editor-interop-extension.js

Fixed the `custom function` validation when using the JSON editor of the Dashboard.

Fixed the `custom function` validation when using the JSON editor of the Dashboard

---

src/dashboard/Synapse.Dashboard/Components/DocumentDetails/Store.cs
src/dashboard/Synapse.Dashboard/Components/MonacoEditor/Store.cs
src/dashboard/Synapse.Dashboard/Components/ResourceEditor/ResourceEditor.razor
src/dashboard/Synapse.Dashboard/Components/WorkflowInstanceCreation/WorkflowInstanceCreation.razor
src/dashboard/Synapse.Dashboard/Components/WorkflowInstancesList/WorkflowInstancesList.razor
src/dashboard/Synapse.Dashboard/Pages/Functions/Create/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Details/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Details/View.razor

Added capability to replay a workflow with the same input in the Dashboard
Also fixed the toast message when copying to clipboard and code formatting when switching to JSON for the first time.

Added capability to replay a workflow with the same input in the Dashboard

---

src/api/Synapse.Api.Client.Core/Services/IClusterResourceApiClient.cs
src/api/Synapse.Api.Client.Core/Services/INamespacedResourceApiClient.cs
src/api/Synapse.Api.Client.Http/Services/ResourceHttpApiClient.cs
src/api/Synapse.Api.Http/ClusterResourceController.cs
src/api/Synapse.Api.Http/NamespacedResourceController.cs
src/cli/Synapse.Cli/Commands/WorkflowInstances/MonitorWorkflowInstancesCommand.cs
src/dashboard/Synapse.Dashboard/Components/ResourceEditor/ResourceEditor.razor
src/runner/Synapse.Runner/Services/Executors/WorkflowProcessExecutor.cs
src/runner/Synapse.Runner/Services/WorkflowExecutionContext.cs
tests/Synapse.UnitTests/Services/MockClusterResourceApiClient.cs
tests/Synapse.UnitTests/Services/MockNamespacedResourceApiClient.cs

- Fixes the API client to use SSEs for watching and monitoring resources
- Fixes the actions to monitor and watch resources using SSEs in both cluster and namespaced resource controllers to flush headers directly
**Additional information**:
This fix is needed because the other, non SSE-based actions, block until the first event is consumed

Fixed the API client to use SSEs for watching and monitoring resources

---

src/api/Synapse.Api.Application/Commands/WorkflowInstances/CancelWorkflowInstanceCommand.cs
src/api/Synapse.Api.Application/Commands/WorkflowInstances/ResumeWorkflowInstanceCommand.cs
src/api/Synapse.Api.Application/Commands/WorkflowInstances/SuspendWorkflowInstanceCommand.cs
src/core/Synapse.Core/WorkflowInstanceStatusPhase.cs
src/operator/Synapse.Operator/Services/WorkflowInstanceHandler.cs
src/runner/Synapse.Runner/Services/RunnerApplication.cs
src/runner/Synapse.Runner/Services/WorkflowExecutionContext.cs
src/runner/Synapse.Runner/Services/WorkflowExecutor.cs
tests/Synapse.UnitTests/Services/MockWorkflowInstanceApiClient.cs

- Adds a new `suspended` workflow instance status phase

Added a new `suspended` workflow instance status phase

---

src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/runner/Synapse.Runner/Services/Executors/ContainerProcessExecutor.cs
src/runner/Synapse.Runner/Services/Executors/ScriptProcessExecutor.cs
src/runner/Synapse.Runner/Services/Executors/ShellProcessExecutor.cs
src/runner/Synapse.Runner/Services/Executors/WorkflowProcessExecutor.cs
src/runner/Synapse.Runner/Synapse.Runner.csproj
tests/Synapse.IntegrationTests/Synapse.IntegrationTests.csproj
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

- Implements the feature to run processes asynchronously without awaiting their completion

Implemented the feature to run processes asynchronously without awaiting their completion

---

src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure.Containers.Docker/Synapse.Core.Infrastructure.Containers.Docker.csproj
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/Synapse.Core.Infrastructure.Containers.Kubernetes.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/dashboard/Synapse.Dashboard/Components/WorkflowInstancesList/WorkflowInstancesList.razor
src/dashboard/Synapse.Dashboard/Extensions/StatusExtensions.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Details/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Details/View.razor
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Synapse.Runner.csproj
src/runtime/Synapse.Runtime.Abstractions/Synapse.Runtime.Abstractions.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

Added suspend/resume/cancel buttons to workflow instances list in the dashboard.

Added suspend/resume/cancel actions to workflow instances in the Dashboard

---

tests/Synapse.UnitTests/Cases/Conformance/Features/BranchFeatureTests.cs
tests/Synapse.UnitTests/Cases/Conformance/Features/branch.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/call.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/data-flow.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/do.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/emit.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/flow.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/for.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/raise.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/set.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/switch.feature
tests/Synapse.UnitTests/Cases/Conformance/Features/try.feature
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

Updated conformance tests to correspond the specification's latest.

Updated conformance tests

---

src/core/Synapse.Core/Extensions/WorkflowDefinitionEnumerableExtensions.cs

Fixed the `WorkflowDefinitionEnumerableExtensions` by using the `SemVersio.PrecendenceComparer` when ordering versions of a workflow

Fixed the `WorkflowDefinitionEnumerableExtensions` by using the `SemVersio.PrecendenceComparer` when ordering versions of a workflow

---

src/runner/Synapse.Runner/Services/Executors/ForTaskExecutor.cs

- Fixes the `ForTaskExecutor`, which was not properly running when the list to enumerate contained only 1 item

Fixed the `ForTaskExecutor`, which was not properly running when the list to enumerate contained only 1 item

---

src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/dashboard/Synapse.Dashboard/Components/WorkflowDiagram/StartNodeViewModel.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/State.cs
src/dashboard/Synapse.Dashboard/Services/WorkflowGraphBuilder.cs
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/runner/Synapse.Runner/Synapse.Runner.csproj
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

Refactors the way the graph is built to handle `if` clauses. Entry and exit ports have been added to cluster nodes to facilitate conditional "branching" and "rejoining".
Closes #409

Properly handled `if` clauses the Dashboard's graph builder

---

src/dashboard/Synapse.Dashboard/Pages/Functions/Create/State.cs
src/dashboard/Synapse.Dashboard/Pages/Functions/Create/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Functions/Create/View.razor
src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/State.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/View.razor

This PR introduces an improvement in the workflow creation/update page of the Synapse Dashboard by optimizing the API call behavior.
Previously, the application relied on calling the API to check if a workflow definition already existed, leading to a significant number of 404 errors in the logs when the definition was not found. This behavior was suboptimal and caused unnecessary strain on the API.
To address this, a variable in the page's state has been introduced to determine if the workflow needs to be created or updated. In addition, when creating, if a conflict is detected, the process will fallback and try to "update" (= create a new version).
Closes #457

Improved workflow creation vs update process in the Dashboard

---

src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure/Services/XmlSchemaHandler.cs
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/dashboard/Synapse.Dashboard/Services/WorkflowGraphBuilder.cs
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/runner/Synapse.Runner/Program.cs
src/runner/Synapse.Runner/Services/Executors/AsyncApiCallExecutor.cs
src/runner/Synapse.Runner/Services/Executors/FunctionCallExecutor.cs
src/runner/Synapse.Runner/Services/Executors/OpenApiCallExecutor.cs
src/runner/Synapse.Runner/Services/TaskExecutorFactory.cs
src/runner/Synapse.Runner/Services/WorkflowExecutor.cs
src/runner/Synapse.Runner/Synapse.Runner.csproj
tests/Synapse.IntegrationTests/Synapse.IntegrationTests.csproj
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

- Implements the `AsyncAPI` function call
**Additional informations**:
- Requires updating the `ServerlessWorkflow` specification's `AsyncApiCallDefinition` to fully support both `AsyncAPI` `v2.6.0` and `v3.0.0` versions (see https://github.com/serverlessworkflow/specification/issues/1045)

Implement the `AsyncAPI` function call

---

src/runner/Synapse.Runner/Services/Executors/HttpCallExecutor.cs

- Fixes the HttpCallExecutor to configure authentication on the HttpClient used to perform the configured request

Fix the HttpCallExecutor to configure authentication on the HttpClient used to perform the configured request

---

src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Resources/CorrelationContext.cs
src/core/Synapse.Core/Resources/CorrelationSpec.cs
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Services/CorrelationHandler.cs
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/dashboard/Synapse.Dashboard.StateManagement/Synapse.Dashboard.StateManagement.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/operator/Synapse.Operator/Services/WorkflowInstanceController.cs
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/IStreamedCloudEvent.cs
src/runner/Synapse.Runner/Services/ConnectedWorkflowExecutionContext.cs
src/runner/Synapse.Runner/Services/Executors/AsyncApiCallExecutor.cs
src/runner/Synapse.Runner/Services/Executors/ListenTaskExecutor.cs
src/runner/Synapse.Runner/Services/Interfaces/ITaskExecutionContext.cs
src/runner/Synapse.Runner/Services/Interfaces/IWorkflowExecutionContext.cs
src/runner/Synapse.Runner/Services/StandAloneWorkflowExecutionContext.cs
src/runner/Synapse.Runner/Services/TaskExecutionContext.cs
src/runner/Synapse.Runner/StreamedCloudEvent.cs
src/runner/Synapse.Runner/Synapse.Runner.csproj
tests/Synapse.IntegrationTests/Cases/Api/Controllers/NamespacesControllerTests.cs
tests/Synapse.IntegrationTests/Cases/Api/Controllers/WorkflowDataControllerTests.cs
tests/Synapse.IntegrationTests/Cases/Api/Controllers/WorkflowInstancesControllerTests.cs
tests/Synapse.IntegrationTests/Cases/Api/Controllers/WorkflowsControllerTests.cs
tests/Synapse.IntegrationTests/Synapse.IntegrationTests.csproj
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

- Implement streaming features for the `listen` task and for the `asyncapi` call, as per https://github.com/serverlessworkflow/specification/pull/1070

Implement streaming features for the `listen` task and for the `asyncapi` call

---

src/runner/Synapse.Runner/Services/Executors/ListenTaskExecutor.cs

- Implements event read mode, as per https://github.com/serverlessworkflow/specification/issues/1068

Implement event read mode

---

src/dashboard/Synapse.Dashboard/Pages/Functions/Create/Store.cs
src/dashboard/Synapse.Dashboard/Services/SpecificationSchemaManager.cs

- Fixes the workflow schema validation, which was using obsolete URIs to get the schema files

Fix the workflow schema validation, which was using obsolete URIs to get the schema files

---

src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure.Containers.Docker/Synapse.Core.Infrastructure.Containers.Docker.csproj
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/Synapse.Core.Infrastructure.Containers.Kubernetes.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Services/TaskExecutor.cs
src/runner/Synapse.Runner/Synapse.Runner.csproj
src/runtime/Synapse.Runtime.Abstractions/Synapse.Runtime.Abstractions.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj

- Fixes the `TaskExecutor` to ignore both `output.as` and `export.as` clauses for skipped tasks

Fix the `TaskExecutor` to ignore both `output.as` and `export.as` clauses for skipped tasks

---

src/dashboard/Synapse.Dashboard/Components/DocumentDetails/Store.cs
src/dashboard/Synapse.Dashboard/Components/MonacoEditor/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Functions/Create/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Functions/Create/View.razor
src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/Store.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Create/View.razor
src/dashboard/Synapse.Dashboard/Pages/Workflows/Details/Store.cs
src/dashboard/Synapse.Dashboard/Services/SpecificationSchemaManager.cs

Aligned Blazor application state with DOM state to prevent issues like 'Couldn't find the editor with id...' or 'Editor with ID "..." not found'.

Fixes "editor not found" errors in the Dashboard

---

src/runner/Synapse.Runner/Extensions/DoTaskDefinitionExtensions.cs
src/runner/Synapse.Runner/Extensions/WorkflowDefinitionExtensions.cs
src/runner/Synapse.Runner/Services/ConnectedWorkflowExecutionContext.cs

- Fixes the `WorkflowDefinitionExtensions` and `DoTaskDefinitionExtensions` to rely on name to determine the next task, instead of relying of task record equality, which resulted in wrong resolution when the task had similar properties

Fix the `WorkflowDefinitionExtensions` and `DoTaskDefinitionExtensions` to rely on name to determine the next task

---

src/runner/Synapse.Runner/Services/Executors/ScriptProcessExecutor.cs

- Fixes the `ScriptProcessExecutor` to honor the `await` property

Fix the `ScriptProcessExecutor` to honor the `await` property

---

src/api/Synapse.Api.Application/Synapse.Api.Application.csproj
src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj
src/api/Synapse.Api.Client.Http/Synapse.Api.Client.Http.csproj
src/api/Synapse.Api.Http/Synapse.Api.Http.csproj
src/api/Synapse.Api.Server/Synapse.Api.Server.csproj
src/cli/Synapse.Cli/Synapse.Cli.csproj
src/core/Synapse.Core.Infrastructure.Containers.Docker/Synapse.Core.Infrastructure.Containers.Docker.csproj
src/core/Synapse.Core.Infrastructure.Containers.Kubernetes/Synapse.Core.Infrastructure.Containers.Kubernetes.csproj
src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj
src/core/Synapse.Core/Synapse.Core.csproj
src/correlator/Synapse.Correlator/Synapse.Correlator.csproj
src/dashboard/Synapse.Dashboard/Synapse.Dashboard.csproj
src/operator/Synapse.Operator/Synapse.Operator.csproj
src/runner/Synapse.Runner/Services/ConnectedWorkflowExecutionContext.cs
src/runner/Synapse.Runner/Services/Executors/ListenTaskExecutor.cs
src/runner/Synapse.Runner/Synapse.Runner.csproj
src/runtime/Synapse.Runtime.Abstractions/Synapse.Runtime.Abstractions.csproj
src/runtime/Synapse.Runtime.Docker/Synapse.Runtime.Docker.csproj
src/runtime/Synapse.Runtime.Kubernetes/Synapse.Runtime.Kubernetes.csproj
src/runtime/Synapse.Runtime.Native/Synapse.Runtime.Native.csproj
tests/Synapse.IntegrationTests/Synapse.IntegrationTests.csproj
tests/Synapse.UnitTests/Synapse.UnitTests.csproj

- Fixed the `ListenTaskExecutor`, which did not work anymore without streaming, due to an invalid condition check
- Fixed the `ListenTaskExecutor`, which failed to read the content of events when the `ListenTask`'s `Read` property was not set.
- Fixed the `ListenTaskExecutor`, which was reading the payload of CloudEvents, even when the `ListenTask`'s `Read` property was set to `envelope`

Fix the `ListenTaskExecutor`, which did not work anymore without streaming

---

src/dashboard/Synapse.Dashboard/Components/HorizontalCollapsible/HorizontalCollapsible.razor
src/dashboard/Synapse.Dashboard/Pages/Workflows/Details/View.razor

Collapsing the workflow details panels when an instance is clicked.
Closes  #455

Workflow details panels auto collapse in the Dashboard

---

src/dashboard/Synapse.Dashboard/Components/ResourceManagement/NamespacedResourceManagementComponentState.cs
src/dashboard/Synapse.Dashboard/Components/ResourceManagement/NamespacedResourceManagementComponentStore.cs
src/dashboard/Synapse.Dashboard/Pages/Workflows/Details/View.razor

Disabled unnecessary namespace listing in the workflow details view.
Closes #458

Disabled unnecessary namespace listing in the Dashboard

---

src/runner/Synapse.Runner/Program.cs
src/runner/Synapse.Runner/Services/Executors/FunctionCallExecutor.cs
src/runner/Synapse.Runner/Services/Executors/HttpCallExecutor.cs

- Fixes the `FunctionCallExecutor` to support custom functions that do not specify an @ catalog, falling back to the default Serverless Workflow catalog
- Fixes the `HttpCallExecutor` to properly evaluate string-based body
- Registers a method used to fetch unresolved JsonSchemas

Fixed the `FunctionCallExecutor` to support custom functions that do not specify an @ catalog, falling back to the default Serverless Workflow catalog

---

deployments/docker-compose/.env
deployments/docker-compose/docker-compose.yml
src/core/Synapse.Core.Infrastructure.Containers.Docker/DockerContainerPlatform.cs
src/core/Synapse.Core/Resources/DockerRuntimeConfiguration.cs
src/dashboard/Synapse.Dashboard/Layout/MainLayout.razor
src/dashboard/Synapse.Dashboard/Services/JsInterop.cs
src/dashboard/Synapse.Dashboard/wwwroot/index.html
src/runtime/Synapse.Runtime.Docker/Services/DockerRuntime.cs

- Fixes the `DockerRuntime` to apply the provided `HostConfig`, thereby supporting volume mount functionality
- Fixes the `DockerContainerPlatform` to properly initialize containers binds, thereby supporting volume mount functionality
- Fixes the docker-compose deployment by replacing `Garnet` by `Redis`
Fixes #521

Fixed the `DockerRuntime` to apply the provided `HostConfig`, thereby supporting volume mount functionality

---

src/operator/Synapse.Operator/Program.cs
src/operator/Synapse.Operator/Services/Interfaces/IWorkflowController.cs
src/operator/Synapse.Operator/Services/WorkflowController.cs
src/operator/Synapse.Operator/Services/WorkflowInstanceController.cs

- Fixes the `WorkflowInstanceController` not to claim instances of workflows explicitly assigned to other operators
Fixes #525

Fixed the `WorkflowInstanceController` not to claim instances of workflows explicitly assigned to other operators

---

src/dashboard/Synapse.Dashboard/Components/ResourceEditor/ResourceEditor.razor
src/dashboard/Synapse.Dashboard/Components/ResourceManagement/ResourceManagementComponent.cs
src/dashboard/Synapse.Dashboard/Pages/Namespaces/List/View.razor
src/dashboard/Synapse.Dashboard/StatefulComponent.cs

Ensure resource editor reflects latest resource state.
Closes #523 

Fixed stale state issue in ResourceEditor after saving

---

src/core/Synapse.Core/Resources/RuntimeDefinition.cs
src/operator/Synapse.Operator/Services/WorkflowInstanceHandler.cs
src/operator/Synapse.Operator/appsettings.Development.json
src/runtime/Synapse.Runtime.Kubernetes/Services/KubernetesRuntime.cs

- Fixes the `WorkflowInstanceHandler` to ignore 304 errors when updating workflow instance status

Fixed the `WorkflowInstanceHandler` to ignore 304 errors when updating workflow instance status
